### ISSUE TITLE
nodejs-basics 페이지 오타 제보드립니다.

### ISSUE THREAD

**Issue by JeongYoungHo** [ungmo2/blog#1]
안녕하세요 poiemaweb을 보며 공부하고 있는 학생입니다.
nodejs 설명하는 페이지에서
`node 명령어를 사용하여 app.js를 실행하여 3이 출력되는 것을 확인한다.`
부분에 `app.js`가 아니라` main.js`인 것 같아요.
확인 부탁드립니다.

**Comment by ungmo2** [comment]
감사합니다! 수정하겠습니다~
